language: python

python:
  - "3.6.3"

sudo: required


install:
  - pip install flask


script:
  - python test.py


deploy:
  provider: heroku
  api-key: 
    secure: $HEROKU_API_KEY
  app: simple-unittest