language: python

python:
  - "3.4"

sudo: required

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y
  - sudo apt-get install python3-pip
  - sudo pip3 install flask
  #- sudo pip3 install flask-unittest

script:
  - python3 test.py test