language: python

python:
  - "3.6.3"

sudo: required

#- stage: install flask
install:
  - pip install flask

#- stage: deploy test
script:
  - python test.py

#- stage: deploy heroku
deploy:
  provider: heroku
  api-key: 
    secure: $HEROKU_API_KEY
  app: simple-unittest